name: Compile Frida for iPhone 6s
on:
  push:
    branches:
      - main  # 可以根据你的需求修改触发分支

jobs:
  build:
    runs-on: ubuntu-latest  # 选择一个合适的运行环境，这里以 Ubuntu 为例
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up build environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential python3-pip autoconf automake libtool pkg-config  # 安装必要的编译工具和依赖
          pip3 install meson ninja  # 安装 Meson 和 Ninja 构建系统

      - name: Configure build for arm64e
        run: |
          cd frida-source-directory  # 进入 Frida 源代码目录，需替换为实际路径
          meson setup build --cross-file=arm64e-cross-file.txt  # arm64e-cross-file.txt 需要定义针对 arm64e 的交叉编译配置
          # 交叉编译配置文件示例（arm64e-cross-file.txt）
          # [binaries]
          # c = 'aarch64-apple-darwin20-clang'  # 假设针对 iOS 14 的交叉编译器，需根据实际情况调整
          # cpp = 'aarch64-apple-darwin20-clang++'
          # ar = 'aarch64-apple-darwin20-ar'
          # strip = 'aarch64-apple-darwin20-strip'

      - name: Build Frida
        run: |
          cd build
          ninja
